version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/lazylms
    binary: lazylms-macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: beauNate
    name: lazylms-macos
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Tag}}"

brews:
  - repository:
      owner: beauNate
      name: homebrew-lazylms-macos
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/beauNate/lazylms-macos
    description: "lazylms-macos – Secure Mac-native TUI for LM Studio (Bubble Tea, Liquid Glass UI)"
    license: MIT
    test: |
      system "#{bin}/lazylms-macos", "--help"
    install: |
      bin.install "lazylms-macos"

# Docker configuration for GitHub Container Registry
dockers:
  - image_templates:
      - "ghcr.io/beaunate/lazylms-macos:{{ .Tag }}"
      - "ghcr.io/beaunate/lazylms-macos:v{{ .Major }}"
      - "ghcr.io/beaunate/lazylms-macos:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/beaunate/lazylms-macos:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    skip_push: false

  - image_templates:
      - "ghcr.io/beaunate/lazylms-macos:{{ .Tag }}-arm64"
      - "ghcr.io/beaunate/lazylms-macos:v{{ .Major }}-arm64"
      - "ghcr.io/beaunate/lazylms-macos:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/beaunate/lazylms-macos:latest-arm64"
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    skip_push: false

docker_manifests:
  - name_template: "ghcr.io/beaunate/lazylms-macos:{{ .Tag }}"
    image_templates:
      - "ghcr.io/beaunate/lazylms-macos:{{ .Tag }}-arm64"
      - "ghcr.io/beaunate/lazylms-macos:{{ .Tag }}"
  - name_template: "ghcr.io/beaunate/lazylms-macos:v{{ .Major }}"
    image_templates:
      - "ghcr.io/beaunate/lazylms-macos:v{{ .Major }}-arm64"
      - "ghcr.io/beaunate/lazylms-macos:v{{ .Major }}"
  - name_template: "ghcr.io/beaunate/lazylms-macos:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/beaunate/lazylms-macos:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/beaunate/lazylms-macos:v{{ .Major }}.{{ .Minor }}"
  - name_template: "ghcr.io/beaunate/lazylms-macos:latest"
    image_templates:
      - "ghcr.io/beaunate/lazylms-macos:latest-arm64"
      - "ghcr.io/beaunate/lazylms-macos:latest"
