name: Update Homebrew Tap

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: lazylms-macos
          formula-path: Formula/lazylms-macos.rb
          homebrew-tap: beauNate/homebrew-lazylms-macos
          base-branch: main
          download-url: ${{ github.event.release.tarball_url }}
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
